title: "RenWolf5 Photography"
description: "A modern photography portfolio and blog."
url: "https://RenWolf5.github.io"

# Collections for easy portfolio updating
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

markdown: kramdown
highlighter: rouge
